import turtle

# turtle.circle(50)
# turtle.done()
tom = turtle.Turtle()
tom.circle(100)
tan = turtle.Turtle()
fun = turtle.Turtle()
tan.shape('circle')
fun.shape('square')
tan.left(30)
tan.forward(100)
fun.backward(50)
pot = turtle.Turtle()
pot.setpos(-100, -100)
pot.forward(30)
pot.forward(30)
tan.clear()
fun.clear()
pot.clear()
fun.shape('triangle')
pot.shape("square")
turtle.done()
